Project Setup
Carshy/dollarGuard-budget-app pull request #1
Opened 2022-11-23 03:28 UTC by Carshy

In this project, I setup rubocop and rails

2022-11-26 20:15 UTC, Carshy commented
I would kindly like to report that Heroku is not responding to my deployment and that limits me to put the live link currently. Kindly allow me to post the link later once the process is complete. It keeps uploading for hours and throws errors. I will update it soon when I sort it out. Thank you

2022-11-26 20:39 UTC, VICTOR-CHUKWU requested changes
Hi @Carshy , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
## Highlights
- [ ] Linters passed
- [ ] correct Git flow
- [ ] Clean code base


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-11-26 20:39 UTC, VICTOR-CHUKWU commented on spec/requests/categories_spec.rb
> +      expect(response.body).to include('DETAILS')
- [ ] All tests are failing, kindly fix this and submit as you have done a fantastic job :clap: 
![image](https://user-images.githubusercontent.com/66097371/204108054-67203f90-94d0-4671-b0c3-af474bccfbce.png)

2022-11-26 23:00 UTC, Carshy commented
All changes made as requested

2022-11-26 23:44 UTC, OLIPLICHE requested changes
Hi @Carshy, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- The App is working fine 💯 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-26 23:44 UTC, OLIPLICHE commented on spec/models/category_spec.rb
> +
- Hi, Please the test still failing. Kindly fix it as requested by the previous review. 
- 
![Capture](https://user-images.githubusercontent.com/63972670/204112869-6371bcf4-5e61-49dc-9249-facd30a9d1c2.JPG)

2022-11-28 10:31 UTC, Carshy commented
All changes made as requested and the test are now passing. Please note this is last week's project and I have spoken to Microver admins Marco Lizza who has told me to submit for approval so that I am progressed to the next module. Thank you

2022-11-28 10:41 UTC, prolajumokeoni commented
Hi @Carshy, kindly add a screenshot of the message you got 👍🏿

2022-11-28 10:49 UTC, Carshy commented
Hello @prolajumokeoni as requested attached herein is the screenshot of the email from Marco Lizza (Microverse Admin):
![image](https://user-images.githubusercontent.com/45807521/204259285-9b533308-8ce6-4cb8-864c-c02c4622efca.png)

2022-11-28 11:12 UTC, prolajumokeoni approved these changes
Hi @Carshy

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Git flow was used correctly 🚀 
- Good Readme 🥇 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Deploying your application so users can view your app online, this will make your app more accessible 👍🏿  

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-28 11:49 UTC, merged